import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { notFound } from "next/navigation";
import { initiatives } from "../../../lib/site";
import { Reveal } from "../../../components/Reveal";

export function generateStaticParams(){return initiatives.map(i=>({slug:i.slug}));}
export default async function InitiativePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const item=initiatives.find(i=>i.slug===slug); if(!item) notFound(); return <div><section className="relative min-h-[480px] overflow-hidden"><Image src={item.image} alt={item.titleEn} fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-slate-950/60"/><div className="container-page relative flex min-h-[480px] items-end pb-14 text-white"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-orange-300">Sadhna Foundation • Initiative</p><h1 className="mt-3 font-display text-5xl font-bold md:text-7xl">{item.titleEn}</h1><p className="mt-2 text-2xl font-semibold text-emerald-200">{item.titleHi}</p><p className="mt-5 max-w-2xl text-lg leading-8 text-white/85">{item.description}</p></div></div></section><section className="container-page py-20"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="text-sm font-bold uppercase tracking-wider text-orange-600">Programme focus</p><h2 className="mt-2 font-display text-4xl font-bold">{item.kicker}</h2><p className="mt-5 leading-8 text-slate-600">Our approach is designed to be practical, locally relevant and measurable. This page is ready for programme-specific outcomes, beneficiary stories, event schedules, partner details and verified metrics as the foundation publishes them.</p><div className="mt-7 grid gap-3">{["Community-led activities", "Inclusive access and participation", "Documented outcomes", "Volunteer and partner engagement"].map(x=><div key={x} className="flex gap-3 rounded-2xl bg-slate-50 p-4 font-semibold"><CheckCircle2 className="shrink-0 text-emerald-600"/>{x}</div>)}</div></Reveal><Reveal delay={.08}><div className="rounded-3xl bg-gradient-to-br from-orange-50 to-emerald-50 p-8"><p className="text-sm font-bold uppercase tracking-wider text-slate-500">Get involved</p><h3 className="mt-2 font-display text-3xl font-bold">Turn concern into action.</h3><p className="mt-3 leading-7 text-slate-600">Support this initiative with a donation, volunteer your skills or partner with the foundation.</p><div className="mt-6 grid gap-3"><Link href="/donate" className="flex items-center justify-between rounded-2xl bg-orange-600 px-5 py-3 font-bold text-white">Support this work <ArrowRight size={18}/></Link><Link href="/volunteer" className="flex items-center justify-between rounded-2xl border border-emerald-600 px-5 py-3 font-bold text-emerald-700">Volunteer <ArrowRight size={18}/></Link></div></div></Reveal></div></section></div>}
