import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Eye, HandHeart, ShieldCheck } from "lucide-react";
import { SectionHeading } from "../../components/SectionHeading";
import { Reveal } from "../../components/Reveal";
import { site } from "../../lib/site";

export default function About(){return <div><InnerHero title="About Sadhna Foundation" hi="सेवा ही साधना है • मानवता ही हमारा धर्म है" image="/images/education.webp"/><section className="container-page py-20"><div className="grid items-center gap-12 lg:grid-cols-2"><Reveal><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image src="/images/women-2.webp" alt="Women working together in a skills programme" fill className="object-cover"/></div></Reveal><Reveal delay={.08}><SectionHeading eyebrow="Who we are" title="A community-first foundation" hi="समुदाय के साथ, समुदाय के लिए"/><p className="mt-5 leading-8 text-slate-600">Sadhna Foundation is a registered non-profit organisation working toward a more educated, healthier, greener and empowered society. We focus on practical community programmes that create opportunities and strengthen local participation.</p><p className="mt-4 leading-8 text-slate-600">Our work spans education, women’s empowerment, healthcare, environmental stewardship and sports-led youth development.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Value icon={<HandHeart/>} title="Service" text="सेवा"/><Value icon={<Eye/>} title="Values" text="संस्कार"/><Value icon={<ShieldCheck/>} title="Trust" text="पारदर्शिता"/></div></Reveal></div></section><section className="bg-slate-50 py-20"><div className="container-page"><SectionHeading eyebrow="Leadership" title="People behind the mission" hi="नेतृत्व और जिम्मेदारी"/><div className="mt-8 rounded-3xl bg-white p-8 shadow-soft md:flex md:items-center md:justify-between"><div><p className="text-sm font-bold uppercase tracking-wider text-orange-600">CEO / Leadership</p><h3 className="mt-2 font-display text-3xl font-bold">{site.leadership}</h3><p className="mt-3 max-w-2xl leading-7 text-slate-600">Leadership details, board information and governance documents can be expanded here as the foundation publishes its official materials.</p></div><Link href="/legal" className="mt-6 inline-flex items-center gap-2 font-bold text-orange-700 md:mt-0">View transparency <ArrowRight size={17}/></Link></div></div></section></div>}
function InnerHero({title,hi,image}:{title:string;hi:string;image:string}){return <section className="relative h-[360px] overflow-hidden bg-slate-900"><Image src={image} alt="" fill className="object-cover"/><div className="absolute inset-0 bg-slate-950/65"/><div className="container-page relative flex h-full items-end pb-12 text-white"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-orange-300">Sadhna Foundation</p><h1 className="mt-2 font-display text-4xl font-bold md:text-6xl">{title}</h1><p className="mt-3 text-lg font-semibold text-emerald-200">{hi}</p></div></div></section>}
function Value({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-orange-600">{icon}</div><p className="mt-2 font-bold">{title}</p><p className="text-xs text-slate-500">{text}</p></div>}
