import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, FileCheck2, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { Hero } from "../components/Hero";
import { SectionHeading } from "../components/SectionHeading";
import { InitiativeCard } from "../components/InitiativeCard";
import { Reveal } from "../components/Reveal";
import { initiatives, site } from "../lib/site";

export default function Home() {
  return <>
    <Hero/>
    <section className="relative -mt-10 z-10"><div className="container-page"><div className="grid gap-3 rounded-3xl border border-slate-100 bg-white p-4 shadow-2xl md:grid-cols-[1.3fr_1fr_1fr]"><div className="flex items-center gap-4 rounded-2xl bg-orange-50 p-5"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-orange-100 text-orange-700"><ShieldCheck/></div><div><p className="text-xs font-bold uppercase tracking-wider text-orange-700">Registered NGO</p><p className="font-bold text-slate-800">Reg. No. {site.registration}</p><p className="text-xs text-slate-500">Registered {site.registrationDate}</p></div></div><div className="flex items-center gap-3 rounded-2xl p-4"><MapPin className="text-orange-600"/><div><p className="text-xs font-bold text-slate-500">Registered Office</p><p className="text-sm font-semibold">Gonda, Uttar Pradesh</p></div></div><div className="flex items-center gap-3 rounded-2xl p-4"><MapPin className="text-emerald-600"/><div><p className="text-xs font-bold text-slate-500">Operational Office</p><p className="text-sm font-semibold">Noida, Uttar Pradesh</p></div></div></div></div></section>

    <section className="container-page py-24"><SectionHeading eyebrow="What we do" title="Our Initiatives" hi="हमारे प्रमुख कार्य क्षेत्र"/><p className="mt-4 max-w-2xl text-slate-600">Five connected pillars designed to address opportunity, wellbeing and community resilience—from the classroom to the playing field.</p><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{initiatives.map((item, i)=><InitiativeCard key={item.slug} item={item} index={i}/>)}</div></section>

    <section className="bg-slate-900 py-24 text-white"><div className="container-page grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><Reveal><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem]"><Image src="/images/environment.webp" alt="Community members planting a tree beside water" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/50 to-transparent"/></div></Reveal><Reveal delay={.08}><p className="text-sm font-bold uppercase tracking-[.18em] text-orange-400">Our philosophy</p><h2 className="mt-3 font-display text-4xl font-bold md:text-5xl">“अंतः अस्ति प्रारंभः”</h2><p className="mt-2 text-lg font-semibold text-emerald-300">The end is where the beginning begins.</p><p className="mt-6 text-lg leading-8 text-slate-300">We believe lasting change begins when service becomes a shared habit. Our programmes bring people, skills and local action together so communities can build a healthier and more resilient future.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 font-bold text-slate-900">Know Our Story <ArrowRight size={18}/></Link></Reveal></div></section>

    <section className="container-page py-24"><div className="grid gap-8 lg:grid-cols-[1fr_.85fr]"><Reveal><SectionHeading eyebrow="Trust & transparency" title="A foundation built on accountability" hi="विश्वास, पारदर्शिता और जिम्मेदारी"/><p className="mt-5 max-w-xl leading-7 text-slate-600">We are committed to maintaining clear registration information, programme documentation, donor communication and responsible use of resources. Add your audited reports, certificates and 80G documentation here as they become available.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Trust text="Registration details published"/><Trust text="Programme records can be documented"/><Trust text="Donation receipts & reporting"/><Trust text="Contactable operational office"/></div><Link href="/legal" className="mt-7 inline-flex items-center gap-2 font-bold text-orange-700">View Legal & Transparency <ArrowRight size={17}/></Link></Reveal><Reveal delay={.08}><div className="rounded-3xl border border-orange-100 bg-gradient-to-br from-orange-50 to-emerald-50 p-8 shadow-soft"><FileCheck2 className="text-orange-600" size={34}/><p className="mt-5 text-sm font-bold uppercase tracking-wider text-slate-500">Registration</p><p className="mt-1 font-display text-4xl font-bold text-slate-900">{site.registration}</p><p className="mt-2 text-sm text-slate-600">Registered on {site.registrationDate}</p><div className="my-7 h-px bg-slate-200"/><p className="text-sm font-bold text-slate-700">Registered office</p><p className="mt-1 text-sm leading-6 text-slate-600">{site.registeredOffice}</p></div></Reveal></div></section>

    <section className="bg-orange-50 py-24"><div className="container-page"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionHeading eyebrow="Upcoming community action" title="Events & Camps" hi="आगामी कार्यक्रम"/><Link href="/contact" className="inline-flex items-center gap-2 font-bold text-orange-700">Suggest an event <ArrowRight size={17}/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Event date="15" month="NOV" title="निःशुल्क स्वास्थ्य शिविर" desc="General medicine, BP, sugar, eye & dental screening." place="Noida, Uttar Pradesh" image="/images/health.webp"/><Event date="22" month="NOV" title="वृक्षारोपण अभियान" desc="Community plantation and clean-water awareness drive." place="Uttar Pradesh" image="/images/environment.webp"/><Event date="05" month="DEC" title="महिला कौशल प्रशिक्षण" desc="Tailoring, sewing and entrepreneurship orientation." place="Uttar Pradesh" image="/images/women.webp"/></div></div></section>

    <section className="container-page py-24"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-r from-orange-600 to-orange-500 p-8 text-white md:p-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><Sparkles className="mb-4 text-orange-100"/><h2 className="font-display text-3xl font-bold md:text-5xl">Be part of the change.</h2><p className="mt-3 max-w-2xl text-white/85">Support a programme, volunteer your skills, or help us build stronger community partnerships.</p></div><div className="flex flex-wrap gap-3"><Link href="/donate" className="rounded-full bg-white px-5 py-3 font-bold text-orange-700">Support Our Mission</Link><Link href="/volunteer" className="rounded-full border border-white/50 px-5 py-3 font-bold text-white">Join as Volunteer</Link></div></div></div></section>
  </>;
}
function Trust({text}:{text:string}){return <div className="flex gap-2 rounded-2xl bg-slate-50 p-3 text-sm font-semibold text-slate-700"><CheckCircle2 size={18} className="shrink-0 text-emerald-600"/>{text}</div>}
function Event({date,month,title,desc,place,image}:{date:string;month:string;title:string;desc:string;place:string;image:string}){return <article className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative aspect-[16/8]"><Image src={image} alt="" fill className="object-cover" sizes="(max-width: 768px) 100vw, 33vw"/></div><div className="flex gap-4 p-5"><div className="h-fit rounded-xl bg-orange-50 px-3 py-2 text-center"><b className="block text-2xl text-orange-700">{date}</b><span className="text-[10px] font-black text-slate-500">{month}</span></div><div><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{desc}</p><p className="mt-2 text-xs font-bold text-emerald-700">{place}</p></div></div></article>}
